### ISSUE TITLE
hljs is not defined in Angular CLI with service

### ISSUE THREAD

**Issue by Dok11** [Useful-Software-Solutions-Ltd/angular2-highlight-js#11]
Angular CLI. ver.4
Error `ERROR ReferenceError: hljs is not defined`:

![image](https://cloud.githubusercontent.com/assets/2697890/26276494/3c2286c8-3d81-11e7-9c85-f5c7536b3b49.png)
![image](https://cloud.githubusercontent.com/assets/2697890/26276521/c2d89310-3d81-11e7-8b05-0425b3de8942.png)

And my code:
```
_setBlog(post) { // from route subscribe() therefore setTimeout();
	this.post = post;
	setTimeout(() => {
		this.highlightJsService.highlight(this.el.nativeElement.querySelectorAll('pre>code'));
	}, 10);
}
```

**Comment by JayChase** [comment]
Hi. This is normally an issue with higlight,js not having been loaded. Please see the demo plunk and recrete if necessary using it.
