### ISSUE TITLE
Angular-cli not found file system.config.js

### ISSUE THREAD

**Issue by lozthiensu** [Useful-Software-Solutions-Ltd/angular2-highlight-js#3]
I use lastest version of angular-cli. And i can't find system.config.js. Please explain how i config it?

**Comment by johnedvard** [comment]
Have you followed the beginners guide at Angular2's home page: https://angular.io/docs/ts/latest/quickstart.html? They instruct you how to create your system.config.js file. And then you modify it with the instructions found on this repository.

**Comment by lozthiensu** [comment]
The lastest angular-cli no have system.config.js. But i did it with a different way. tks

**Comment by JayChase** [comment]
Hi. Sorry I haven't been around for a while. I was able to use the module with angular-cli by adding it to angular-cli.json and using the relative path for the import statement in app.module.ts instead of the SystemJS alias. I've updated the readme with the details.

**Comment by lozthiensu** [comment]
it package very good, but after install it, my component will lag and slowly when type text to a input in component, and i remove it :(

**Comment by JayChase** [comment]
I guess that might be to do with your other issue with ngFor? I will have a look to see if I can find any way of improving the performance.

**Comment by lozthiensu** [comment]
i use observable, ngFor(but it just have one element in observable), and use pipe to bind trust html(my content include all code highlight in observable or normal text, if i have multi statement(>2) code tag, it will slowly and lag). I use service to show highlight auto.


Waiting for you fix it :)

**Comment by johnedvard** [comment]
Maybe this is related to #4?
