### ISSUE TITLE
peerDependencies angular/core: 2.0.0

### ISSUE THREAD

**Issue by oleg-sevenval** [Useful-Software-Solutions-Ltd/angular2-highlight-js#6]
npm always yells at me because I have a not matching peer dependency in my package.json. Is there a particular reason why you have set the peerDependence to the exact version of angular/core 2.0.0? Why not with the caret or tilde prefix?

**Comment by JayChase** [comment]
Hi. I've got some cleaning up to do to move the module to the latest recommendations for angular-cli. I'll leave this open and change the dependencies for the next version.

**Comment by oleg-sevenval** [comment]
Sounds good, thanks 👌

**Comment by kokojvanko** [comment]
Is there any ETA on when the next version is going to come out? Im trying to use this module with 2.4.3 and up and i cant. Thanks

**Comment by JayChase** [comment]
The peer dependencies are removed as of version 5.0.0. It makes it easier to maintain and I can't imagine many people trying to use the package without Angular x installed.

**Comment by JayChase** [comment]
There isn't too much I can do to control the change control in a directive. In the parent component you could the change detection strategy to OnPush to reduce the number of time ngAfterViewChecked gets called (see [here](https://juristr.com/blog/2016/04/angular2-change-detection/) for more information).
